Update EMI_table.py
Data initialization using pd.DataFrame(). Was failing on Streamlit deploy due to:

table = table.append(data, True)
AttributeError: 'DataFrame' object has no attribute 'append'